name: Unit tests

on: pull_request

jobs:

  unit-tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Update Packages
      run: |
        sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo apt-get install -y libcppunit-dev
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Fetch base branch
      run: |
        git remote add upstream "https://github.com/${{ github.event.pull_request.base.repo.full_name }}"
        git fetch --no-tags --no-recurse-submodules upstream "${{ github.event.pull_request.base.ref }}"
    - name: Configure Project
      run: |
        libtoolize
        aclocal -I scripts
        autoconf -i
        autoheader
        automake --add-missing
        ./configure
    - name: Build Project
      run: |
        make
    - name: Run Unit Tests
      run: |
        make check
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          brew install automake cppunit libtool

      - name: Compile and Test
        run: |
          autoreconf -fiv
          ./configure
          make
          make check
  DragonflyBSD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/dragonflybsd-vm@v1
        with:
          prepare: |
            pkg install -y automake autoconf cppunit libtool openssl pkgconf
          run: |
            autoreconf -fiv
            ./configure
            make
            make check
  FreeBSD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          prepare: |
            pkg install -y automake autoconf cppunit libtool openssl pkgconf
          run: |
            autoreconf -fiv
            ./configure
            make
            make check
  NetBSD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/netbsd-vm@v1
        with:
          release: '10.0'
          prepare: |
            /usr/sbin/pkg_add automake autoconf cppunit libtool openssl pkgconf
          run: |
            autoreconf -fiv
            ./configure
            make
            make check
  OpenBSD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/openbsd-vm@v1
        with:
          prepare: |
            pkg_add automake autoconf-2.72p0 cppunit libtool openssl pkgconf
          run: |
            env AUTOCONF_VERSION=2.72 autoreconf -fiv
            ./configure
            make
            make check
  Alpine:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: ['x86_64', 'x86', 'armhf', 'armv7', 'aarch64', 'ppc64le', 'riscv64', 's390x']
    defaults:
      run:
        shell: alpine.sh {0}
    steps:
      - uses: actions/checkout@v4
      - uses: jirutka/setup-alpine@v1
        with:
          branch: edge
          arch: ${{matrix.platform}}
          packages: >
            build-base automake autoconf cppunit-dev libtool linux-headers openssl-dev pkgconf zlib-dev
      - name: Compile and Test
        run: |
          autoreconf -fiv
          ./configure
          make
          make check
